Feature: Add aggregation functions into filters and withs.
egal/framework-php-package pull request #174
Opened 2021-11-12 05:45 UTC by annstgn

… and withs

2021-11-13 14:26 UTC, annstgn commented
В пт нашли баг при запросе одновременно и filter и withs с агрегатными функциями

2021-11-15 03:21 UTC, annstgn commented
> В пт нашли баг при запросе одновременно и filter и withs с агрегатными функциями

Пофиксила, добавила в тест случаи использования фильтров с withs

2021-11-15 03:37 UTC, rollsover requested changes
Слишком сложно. Переделывать.

2021-11-15 03:37 UTC, rollsover commented on src/Model/Builder.php
> +            $this->setFromSubWithAggregateRelationFilter($filterPart->getAggregateRelations());
Должно быть внутри `setFilter()`

2021-11-25 04:19 UTC, rollsover commented
Нужно переделывать

2021-11-25 04:19 UTC, closed without merging